import {
  MigrationInterface,
  QueryRunner,
} from "typeorm";

import { Articulo } from "./../entity/articulo";

export class seedArticulos1635197153829 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const articulos: Articulo[] = [
      {
        "codart": 1,
        "uniart": 0,
        "descrip": "CODIGO MERCADERIA - PRUEBA",
        "valor": 0,
        "resto": 1,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 1,
        "codprecan": "CJ",
        "codpreres": "",
        "factor": 0,
      },
      {
        "codart": 462,
        "uniart": 1,
        "descrip": "ECCO CEBADA 58GR*48UN",
        "valor": 0.058,
        "resto": 48,
        "unipaq": 2,
        "unidmin": 0,
        "peso": 0.06,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 470,
        "uniart": 1,
        "descrip": "SEMOLA MOLITALIA 20UN*200GR",
        "valor": 0.2,
        "resto": 20,
        "unipaq": 0,
        "unidmin": 20,
        "peso": 4,
        "codprecan": "PQ",
        "codpreres": "UN",
        "factor": 20,
      },
      {
        "codart": 471,
        "uniart": 1,
        "descrip": "ALACENA MAYON 12UN*475GR",
        "valor": 0.5,
        "resto": 12,
        "unipaq": 0.5,
        "unidmin": 0,
        "peso": 6,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 481,
        "uniart": 1,
        "descrip": "3 OSITO AV/ MACA 12UN*170GR",
        "valor": 0.17,
        "resto": 12,
        "unipaq": 0.5,
        "unidmin": 0,
        "peso": 2.04,
        "codprecan": "PQ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 486,
        "uniart": 1,
        "descrip": "PRIMOR ACEIT.VEGETALCLASI.1LT*12BOT",
        "valor": 1,
        "resto": 12,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 12,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 488,
        "uniart": 1,
        "descrip": "BOLIVAR DET.AV.FLORAL360GR*30UN",
        "valor": 0.36,
        "resto": 30,
        "unipaq": 1.25,
        "unidmin": 0,
        "peso": 10.8,
        "codprecan": "PQ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 489,
        "uniart": 1,
        "descrip": "IDEAL ACEITE 1LT*12BOT",
        "valor": 1,
        "resto": 12,
        "unipaq": 0.5,
        "unidmin": 0,
        "peso": 12,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 491,
        "uniart": 1,
        "descrip": "PRIMOR PREMIUM VEGETAL1LT*12BOT",
        "valor": 1,
        "resto": 12,
        "unipaq": 0.5,
        "unidmin": 0,
        "peso": 12,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 515,
        "uniart": 1,
        "descrip": "FANNY MERM SCH FRS 6DP*12U*100GR",
        "valor": 0.1,
        "resto": 6,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 7.2,
        "codprecan": "CJ",
        "codpreres": "DS",
        "factor": 0,
      },
      {
        "codart": 539,
        "uniart": 1,
        "descrip": "POMAROLA SALS/TOM 24UN*160GR",
        "valor": 0.16,
        "resto": 24,
        "unipaq": 0,
        "unidmin": 6,
        "peso": 3.84,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 545,
        "uniart": 1,
        "descrip": "FANNY MERM DOY PACK 8UN*800GR",
        "valor": 0.8,
        "resto": 8,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 6.4,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 550,
        "uniart": 1,
        "descrip": "FRUNA BLOCKS 12DP*20U*25GR",
        "valor": 0.5,
        "resto": 12,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 6,
        "codprecan": "CJ",
        "codpreres": "DS",
        "factor": 0,
      },
      {
        "codart": 551,
        "uniart": 1,
        "descrip": "GLORIA LCH.FRSC.TETRA.UHTNTR.1L*12UN",
        "valor": 1,
        "resto": 12,
        "unipaq": 0.5,
        "unidmin": 0,
        "peso": 12,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 552,
        "uniart": 1,
        "descrip": "GLORIA LCH.FRSC.TETRA.UHTLIGHT1L*12UN",
        "valor": 1,
        "resto": 12,
        "unipaq": 0.5,
        "unidmin": 0,
        "peso": 12,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 560,
        "uniart": 1,
        "descrip": "GLORIA LCH.LIGHT 1CJ*24UN*400GR",
        "valor": 1,
        "resto": 24,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 0.4,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 564,
        "uniart": 1,
        "descrip": "3 OSITO AV/ KIWICH 12UN*170GR",
        "valor": 0.17,
        "resto": 12,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 2.04,
        "codprecan": "PQ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 566,
        "uniart": 1,
        "descrip": "FRUGOS TETRAPACK  1.5 LT X 8UN",
        "valor": 1.5,
        "resto": 8,
        "unipaq": 0,
        "unidmin": 0,
        "peso": 12,
        "codprecan": "CJ",
        "codpreres": "UN",
        "factor": 0,
      },
      {
        "codart": 568,
        "uniart": 1,
        "descrip": "INKA KOLA GASEOSA1.5LT*6UNID",
        "valor": 1.5,
        "resto": 6,
        "unipaq": 0.25,
        "unidmin": 0,
        "peso": 9,
        "codprecan": "PQ",
        "codpreres": "UN",
        "factor": 0,
      },
    ];

    await queryRunner.manager.save(Articulo, articulos);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("DELETE * FROM articulos");
  }
}
